name: 'Build a Docker image using Spring'
description: 'Build a Docker image using Spring'
inputs:
  java_version:
    description: 'The Java version'
    required: false
    default: '17'
  build_command:
    description: 'The command to build the Docker image'
    required: false
    default: 'mvn -Pnative spring-boot:build-image -DskipTests -Dspring-boot.build-image.publish=false -Dspring-boot.build-image.imageName=application/application:${{ github.sha }}'
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        check-latest: false
        cache: 'maven'
    - name: Build the Docker image
      run: ${{ inputs.build_command }}
      shell: bash
    - name: Save the Docker image
      run: |
        docker save application/application:${{ github.sha }} | gzip > /tmp/application.tar.gz
      shell: bash
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: /tmp/application.tar.gz
        retention-days: 1
