name: 'Build a Java function'
description: 'Build a Java function using Maven'
inputs:
  java_version:
    description: 'The Java version'
    required: false
    default: '17'
  build_command:
    description: 'The command to build the Java project'
    required: false
    default: 'mvn package azure-functions:package -Pprod,azure'
  application_name: 
    description: 'The name of the application that will be deployed'
    required: true  
  resource_group: 
    description: 'The name of the resource group containing the resources'
    required: true      
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java_version }}
        check-latest: false
        cache: 'maven'
    - name: Build with Maven
      run: |
        ${{ inputs.build_command }} \
        -DfunctionResourceGroup=${{ inputs.resource_group }} \
        -DfunctionAppName=${{ inputs.application_name }}
      shell: bash
    - name: Temporarily save package
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: '${{ github.workspace }}/target/*.[j,w]ar'
        retention-days: 1
